### PR TITLE
Add ElasticSearch7 support

### PR DESCRIPTION
**Pull request by heinrichcohn**
PR for issue https://github.com/Netflix/conductor/issues/2030

### CODE REVIEW

**Comment by heinrichcohn** [comment]
Hi @aravindanr @apanicker-nflx 

I haven't received any response from you..

I will like to add two more thing to the code and also to the code i'm preparing for version 3.0.
1)  Basic Authentication: Pass user/password when connecting to ES (configurable in config file)
2)  Read from Aliases:
 -- Add aliases to all indexes and index templates (templates were updated in the project)
 -- Option to read only from aliases. (configurable in config file)
 -- Option to configure prefix of Aliases (configurable in config file)

**Comment by heinrichcohn** [comment]
@apanicker-nflx 
Can you please review this PR? 
Thanks

**Review by apanicker-nflx — APPROVED** [review]
Looks good.
Please add license headers to new files.

**Comment by heinrichcohn** [comment]
@apanicker-nflx
PR was updated. 
- License headers were added
- README file was updated
 
Thanks

**Comment by marcocrasso** [comment]
> I don't see 'es7-persistence' folder in main branch. any plans to make it available ?

I think all will see it when they merge https://github.com/Netflix/conductor/pull/2324 .

**Pull request merged**
