### PR TITLE
Build/optimize express build and deployment

### PR DESCRIPTION
**Pull request by lordbender**
In further preparation for the react 16 upgrade, we can safely modernize the React and Express builds.

1) Move React Build to Facebook's react-scripts to optimize output, tests, HMR, and simplify build complexity while adding build features like import images and css.

2) Stop compiling express application and run the server as native node.

__There is not longer a need to use Webpack, Gulp and babel directly on the ReactJS side__. With the release of the React Scripts we can use the default build, run and test with zero config.

Moreover, with node 8.9.x+ we can stop compiling the express server and just run node server/server.js directly, no transpilation needed.

This will change current deployment and development models slightly.

## Development Process (no more need to use watch script) ##
* npm run server (Handles the Express Hot Reloading and runs the express server)
* npm start (Handles the React HMR and express proxy)
* I added a watch script for any existing users that use watch as part of their process.

Deployment Process:
## npm run build  ##
* copy modules and server directory to the server
* run "node server/server.js" on the remote server

### CODE REVIEW

**Comment by apanicker-nflx** [comment]
@lordbender Thank you very much for the PRs.
This PR would accompany #696 in the major version upgrade.

**Comment by lordbender** [comment]
@apanicker-nflx should I change the target branch? The major version would be a good time to put in the React 16+, React Router and Redux upgrades too.

**Comment by apanicker-nflx** [comment]
@lordbender Please keep the PR pointed to `dev` branch for now. We will be merging the `2.0` branch to dev once it is stable, and we can merge the UI changes into `dev` then.  This would keep a clean separation between the UI and backend changes. Thanks.

**Comment by apanicker-nflx** [comment]
Closing this too, please see #696 for comment.

**Pull request closed without merging**
