### PR TITLE
Update to Java 17

### PR DESCRIPTION
**Pull request by alexmay48**
Pull Request type
----
- [ X ] Feature
- [ X ] Build related changes (Please run `./gradlew generateLock saveLock` to refresh dependencies)

**NOTE**: Please remember to run `./gradlew spotlessApply` to fix any format violations.

Changes in this PR
----
This updates the repo to use Java 17 instead of Java 11. To accomplish this, we do need to pull in the Nashorn Scripting Engine library explicitly to use it. We could consider allowing the users to configure to use their own implementation of a scripting engine, but that can be done in a new feature MR.

### CODE REVIEW

**Comment by alexmay48** [comment]
@v1r3n , this should pass the build check if the Github Actions was setup to use Java 17. Thanks.

**Comment by egandro** [comment]
Any upgrade on this?

**Comment by egandro** [comment]
Any updates on this?

**Comment by egandro** [comment]
@alexmay48 I consider creating a fork since so many many PRs are stalled :(

Are you willing to join forces?

**Comment by alexmay48** [comment]
@egandro 
I am working on this repo because my company relies on it, and so we make changes as needed. I don't think we have a big need to push some of these features through or to rely on a forked repo. You'll have to ask the maintainers about pushing PRs through. I made this Java 17 change because it would be a nice to have, but it's not necessary for us at the moment.

**Comment by v1r3n** [comment]
Hi @alexmay48 we are reviewing, and this should be part of the next release.  JDK 17 is a major update and we need to ensure it preserves backward compatibility.

**Review by v1r3n — APPROVED** [review]

**Comment by v1r3n** [comment]
@alexmay48 do you want to update the GitHub workflows as well to use JDK17?

**Pull request merged**
