### PR TITLE
Added support for building and running docker image for windows in documentation.

### PR DESCRIPTION
**Pull request by dhruv2196**
Pull Request type
----
- [x] Bugfix and Documentation for Windows

Changes in this PR
----
Added support for windows in documentation 

_Describe the new behavior from this PR, and why it's needed_
Issue #3741
./gradlew: not found error when trying to build docker compose on Windows

### CODE REVIEW

**Comment by dhruv2196** [comment]
I have updated the solution as I found another issue when trying to build and run docker compose on windows. 
Initial issue - I was facing an error ./gradlew: not found.
I fixed it by changing the line seperator. So it was able to built it successfully but when I tried to run the server it was again throwing some exceptions. So I found a solution to run these 2 commands and then clone it -
Run git config --global core.autocrlf false;
Run git config --global core.eol lf; (Small L and f)
git clone https://github.com/Netflix/conductor.git
The problem was that when I was trying to clone it on windows then it automatically picks all the files with CRLF line separator. So we need to change it to LF so that scripts can run smoothly via windows on docker.

**Comment by dhruv2196** [comment]
Can anyone please review this PR?

**Comment by Robban1980** [comment]
Running 
```
Run git config --global core.autocrlf false;
Run git config --global core.eol lf; (Small L and f)
```
on windows is not good as it changes the global settings for all repos and will cause issues for any other repo

in a `.gitattributes` file add the following
`gradlew eol=lf
*.gradle eol=lf
*.java eol=lf
*.groovy eol=lf
spring.factories eol=lf
*.sh eol=lf`

then the line endings will not change when the code is pulled.

**Comment by dhruv2196** [comment]
> 

Thanks @Robban1980 for reviewing this. Your suggestion sounds better to me. I will make changes, test and update the PR accordingly.

**Pull request closed without merging**
