### PR TITLE
Fix tasks getting executed multiple times with MySQL storage backend

### PR DESCRIPTION
**Pull request by picaron**
With the current MySQL Queue DAO implementation, tasks sometimes get executed multiple times even if the first attempt ends in success.

This PR is to fix that issue

### CODE REVIEW

**Comment by picaron** [comment]
@v1r3n @vikramsingh2104 please review this small fix for the MySQL persistence implementation

**Comment by picaron** [comment]
thanks @v1r3n are you going to create another 1.8.2 release candidate?

**Comment by v1r3n** [comment]
@picaron yes, we have some pending changes in dev that we are testing.  Should create an RC soon.

**Comment by picaron** [comment]
awesome, thanks 👍

**Pull request merged**
