### PR TITLE
update flyway version

### PR DESCRIPTION
**Pull request by michaelpaliy**
Hi,
Our conductor setup consists of multiple instances. If we start the instances simultaneously, sometimes we got the following error:

```
2021-02-01 12:42:08,339 [main] ERROR error migration DB
org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Script failed
-------------
SQL State  : 23505
Error Code : 0
Message    : ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
  Detail: Key (typname, typnamespace)=(schema_version, 2200) already exists.
Line       : 17
Statement  : CREATE TABLE "public"."schema_version" (
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP NOT NULL DEFAULT now(),
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
) WITH (
  OIDS=FALSE
)

        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.createIfNotExists(MetaDataTableImpl.java:104)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:111)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:175)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at com.netflix.conductor.postgres.PostgresDataSourceProvider.flywayMigrate(PostgresDataSourceProvider.java:94)
        at com.netflix.conductor.postgres.PostgresDataSourceProvider.get(PostgresDataSourceProvider.java:43)
        at com.netflix.conductor.postgres.PostgresDataSourceProvider.get(PostgresDataSourceProvider.java:28)
```

This issue is related to flyway (conductor is using flyway:4.0.3, this issue is fixed in 5.1.0):
https://github.com/flyway/flyway/issues/1067
https://github.com/flyway/flyway/issues/1983

In this PR, I updated the flyway version to the latest one which solves this issue.

### CODE REVIEW

**Comment by apanicker-nflx** [comment]
@mactaggart @rickfish Could you please help with reviewing this PR.

**Comment by rickfish** [comment]
I am a couple of dev versions behind so maybe it is because of that but I made the same changes in the Postgres module and I get this error at startup (we have a schema named conductor-unita in our 'unit' database):

[ERROR] 2021-02-02 14:24:31,388 PostgresDataSourceProvider - error migration DB
org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "conductor_unita" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:196)

**Comment by michaelpaliy** [comment]
Hi @rickfish 
Thanks for the review. 
Flyway changed the default schema history table name from `schema_version` to `flyway_schema_history` https://github.com/flyway/flyway/issues/1848.
So, it's not recognized your history table and you got an error.
I updated the configurations to use `schema_version` as default.
can you pls try to run it again with the new commit?

**Comment by michaelpaliy** [comment]
Hi @rickfish ,
Any update? Did you get a chance to look into it?

**Comment by michaelpaliy** [comment]
Hi @apanicker-nflx / @aravindanr, 
Could you pls review and merge this PR?
This issue blocking us, and force us to work with a forked repo.
We have a requirement to destroy and deploy new conductor clusters which consist of multiple instances, 
When we deploy a new cluster with an empty database we get the following error:
ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
This PR fixes this issue, by updating the flyway version (which causes this bug).

**Pull request merged**
