### PR TITLE
[CORE][ExecutionService] - get task by task type

### PR DESCRIPTION
**Pull request by math29**
Hello,

We would need the ability to get all tasks filtered by taskType without any count from ExecutionService (today on only can get SCHEDULED and IN_PROGRESS tasks with a mandatory count).

Thanks,

Math

### CODE REVIEW

**Comment by math29** [comment]
Hello @vikramsingh2104, do you have any update about this review? :)

**Comment by math29** [comment]
Hello @v1r3n @vikramsingh2104, do you have any news about this PR? :)

**Comment by v1r3n** [comment]
This could lead to huge reads - its quite possible that number of tasks over the period grows to large size (millions).

How about using indexing system in elasticsearch to get the tasks?

**Comment by math29** [comment]
We don't wanna use elasticsearch on our side for now.

@v1r3n what about using SSCAN for getTasks methods (adding 2 parameters to this method for pagination)

**Comment by v1r3n** [comment]
@math29 smembers is going to be an expensive operation if there are many tasks by type.  I recommend switching to SSCAN with start and count (optional) for pagination.  That should work.

**Comment by math29** [comment]
Ok, I'll change my PR to use SSCAN, thank you!

**Pull request closed without merging**
