### PR TITLE
remove id column from tables, set primary key to existing unique index

### PR DESCRIPTION
**Pull request by mactaggart**
This PR removes id column/primary key from conductor MySQL/Postgres tables and replaces pk with unique index of table. MySQL/Postgres DAOs were updated to sort by "created_on" column instead of auto-incremented "id" column. Supersedes #2013 

@kishorebanala @raghavendra-bhat @rickfish

### CODE REVIEW

**Comment by apanicker-nflx** [comment]
@rickfish @raghavendra-bhat could you please help with reviewing this PR?

**Comment by rickfish** [comment]
@apanicker-nflx this looks good to me

**Comment by mactaggart** [comment]
Since #2013 was merged, I updated the migration version number to not conflict

**Comment by mactaggart** [comment]
I see build is failing; looking into this.

**Comment by mactaggart** [comment]
@rickfish @raghavendra-bhat I fixed an issue with the stored procedure for mysql. Ready for review.

**Comment by rickfish** [comment]
@mactaggart we use Postgres, not MySql so I cannot validate this.

**Comment by apanicker-nflx** [comment]
@rickfish Can you please verify the changes to the postgres module?
@mashurex Can you help reviewing the changes to the mysql module?

**Comment by rickfish** [comment]
@apanicker-nflx @mactaggart this looks good to me from a Postgres perspective

**Pull request merged**
