### PR TITLE
Conductor Flyway configuration extension

### PR DESCRIPTION
**Pull request by mashurex**
When using Conductor with an existing schema that is also managed by Flyway, it is difficult to keep them from clashing. This is because the Conductor migrations are on the default Flyway locations path and Flyway uses recursive class path scanning, so it will combine all migrations together leading to version clashes and out of order migration issues.

- Move Postgres and MySQL Flyway migrations from default Flyway location so as not to clash with external Flyway migrations
- Add flyway.locations property to make the locations externally configurable
- Add Flyway baseline migration config parameter to allow Conductor migration in schemas with existing tables
- Update Postgres and MySQL tests to utilize new default locations
- Remove unused MySQL test classes and methods

### CODE REVIEW

**Comment by apanicker-nflx** [comment]
@mashurex Please fix failing tests in the [build](https://travis-ci.com/github/Netflix/conductor/builds/156356932).

@s50600822 @jvemugunta @mactaggart Please help with reviewing this pull request as you are the primary users/contributors to these persistence modules.

**Comment by mashurex** [comment]
@apanicker-nflx It appears the failure was from the Cassandra persistence tests not being able to connect, which were untouched. I'm checking locally to make sure nothing I did caused issues but all PG and MySQL tests were passing.
```
Task :conductor-cassandra-persistence:test
16:29:07.480 [pool-8-thread-1] ERROR c.d.driver.core.RequestHandler - Unexpected error while querying localhost/127.0.0.1
com.datastax.driver.core.exceptions.ConnectionException: [localhost/127.0.0.1:9142] Pool is CLOSING
...
```

**Comment by mactaggart** [comment]
@mashurex suggested changes here: [Review](https://github.com/mashurex/conductor/pull/1)

Cassandra tests passed locally for me but printed errors fixed in PR #1648

**Comment by kishorebanala** [comment]
Hey @mashurex, bumping this up to see if you're still planning to work on this feature.

**Comment by mashurex** [comment]
I am! I honestly forgot about it for a while. I plan to follow the previous advice and split this work into two PRs. I'll use this one for the property changes and open a new one for the other work.

**Comment by mashurex** [comment]
I'm going to close this out completely and re-submit when I get this finished from my side.

**Pull request closed without merging**
