### PR TITLE
Do_while task relevant loop over task calculation fix

### PR DESCRIPTION
**Pull request by manan164**
Pull Request type
----
- [X] Bugfix

**NOTE**: Please remember to run `./gradlew spotlessApply` to fix any format violations.

Changes in this PR
----

_Describe the new behavior from this PR, and why it's needed_
Issue #https://github.com/Netflix/conductor/issues/3271
There was error in calculating the relevant task for do_while task.

### CODE REVIEW

**Comment by manan164** [comment]
Hi @apanicker-nflx , One test is failing, I am working on a fix and also will add a few more tests.

**Comment by charybr** [comment]
Hi @manan164, While testing this change with a existing DoWhile workflow found couple of issues:
1. it stops after first iteration.
2. When testing with 100 iteration loop, usually after 50 iterations, output variable "iteration" doesn't get inserted.

**Comment by manan164** [comment]
Hi @charybr , thanks for reporting. 
For 
1. Is possible for you to share the definition? May be the condition is in such a way that it executes only one iteration or some parsing error.
2. Are you trying to put task output in external storage? The conductor has a limit on that. By default, it is 10MB.
Let me know if this works, or we can chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) for more realtime collaboration.

**Comment by charybr** [comment]
Thank you, for responding.

Attached workflow we are using to test DoWhile, task is a simple sleep task.
[DoWhileLoop.json.txt](https://github.com/Netflix/conductor/files/10912485/DoWhileLoop.json.txt)

We are using Dynomite cluster as persistence.

**Comment by manan164** [comment]
Hi @charybr , I see the execution works fine. 
Can you please try with below definition,
```
{
  "createTime": 1678218111006,
  "updateTime": 1678218236428,
  "name": "TestLoop20221208_63f649c1696f6e2d30e7228c",
  "version": 1,
  "tasks": [
    {
      "name": "serialLoop1",
      "taskReferenceName": "serialLoop1_0",
      "description": "Serial Loop",
      "inputParameters": {
        "iterCount": "100"
      },
      "type": "DO_WHILE",
      "loopCondition": "if ($.serialLoop1_0['iteration'] < $.iterCount ) { true; } else { false; }",
      "loopOver": [
        {
          "name": "InvokeSleepTask_1_63f649c0696f6e2d30e7224b",
          "taskReferenceName": "InvokeSleepTask1_0",
          "description": "Sleep Task",
          "inputParameters": {
            "duration": "2s"
          },
          "type": "WAIT"
        }
      ]
    }
  ],
  "inputParameters": [],
  "outputParameters": {},
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "test@test.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "variables": {},
  "inputTemplate": {}
}
```
For simplicity I have removed other task and input

**Pull request merged**
