### PR TITLE
Oracle Persistence Feature - Community Projects (RELATED.md)

### PR DESCRIPTION
**Pull request by maheshyaddanapudi**
Pull Request type
----

- [x] Feature
- [x] Build related changes
- [x] Other (please describe): Docker / Docker Compose files included.

Changes in this PR
----

- Supports Oracle Database version > 12.2 - Tested well with 19C
- Updated Dockerfile's startup.sh script (java -jar .... | tee server.log) to write logs to both Docker container as well as server.log file.

Feature
--

1. Oracle Persistence / Option to use Oracle Database as persistence unit.
2. Docker Compose example with Oracle Container.

Technical Note
--

1. Utilizes Oracle Database version 11G for Unit Tests 

> Due to GuitHub GI Container disk space limitation, no version > 11G can be used for Unit Tests. 
Can be easily upgraded to 18 XE or 19C Enterprise once GitHub Action updates size capacity which they are apparantly working on).

2. Due to a technical version dependency, spring.flyway.locations cannot be automatically set to db/migration_oracle (similar to postgres-persistence) and **has to be set through .properties file while running the jar along with conductor.db.type**

> Refer to docker/server/config-oracle.properties for example
 
3. Flyway 6.4.4 (5.2+) - Only compatible with Oracle 12.2+
4. Flyway 4.0.3 (<5.2) - Used for Unit Tests as Oracle 11G XE is used for Oracle Container.

Alternatives considered
----

Many other persistence alternatives like Cassandra, MySQL, Postgres already exist. This is just an addition to persistence options.

### CODE REVIEW

**Comment by maheshyaddanapudi** [comment]
Created a cleaner PR

https://github.com/Netflix/conductor/pull/2296

**Comment by maheshyaddanapudi** [comment]
Hi @apanicker-nflx @aravindanr @kishorebanala 

Request your help in reviewing the PR.

**Comment by apanicker-nflx** [comment]
Please resolve conflicts.

**Comment by maheshyaddanapudi** [comment]
> Please resolve conflicts.

Done :)

**Pull request merged**
