### PR TITLE
New workflow metadata endpoint

### PR DESCRIPTION
**Pull request by alexmay48**
Pull Request type
----
- [X] Feature

**NOTE**: Please remember to run `./gradlew spotlessApply` to fix any format violations.

Changes in this PR
----
Adds a new endpoint that allows grabbing all workflows, but only the latest definitions.

_Describe the new behavior from this PR, and why it's needed_
Issue #3642
It provides an endpoint that grabs all workflow definitions, but only their latest versions. This will dramatically decrease payload size when searching all workflows.

Alternatives considered
----

_Describe alternative implementation you have considered_

### CODE REVIEW

**Comment by v1r3n** [comment]
Hi @alexmay48 looks good, but you also want to update other DAOs here or else it will break the build:
https://github.com/Netflix/conductor-community/tree/main/persistence

Another suggestion: Also add this method to the conductor-client.

**Comment by alexmay48** [comment]
@v1r3n To make the fixes to the DAOs in https://github.com/Netflix/conductor-community/tree/main/persistence, won't I need this PR to go through to implement the interface for this? Or is there some process to use a snapshot of the conductor repo for development to implement the MetadataDAO interface for the conductor-community repo? It seems like there is a circular dependency that doesn't seem great for development. Let me know if my question isn't clear. Thanks.

**Comment by v1r3n** [comment]
> @v1r3n To make the fixes to the DAOs in https://github.com/Netflix/conductor-community/tree/main/persistence, won't I need this PR to go through to implement the interface for this? Or is there some process to use a snapshot of the conductor repo for development to implement the MetadataDAO interface for the conductor-community repo? It seems like there is a circular dependency that doesn't seem great for development. Let me know if my question isn't clear. Thanks.

You can use your branch/fork with the changes, publish them to local maven repository `gradlew publishToMavenLocal` and use that version (you can run `gradlew properties` and check for `Inferred project: conductor, version: ` to find the version.

With that you will be able to make the changes.

**Comment by alexmay48** [comment]
> > @v1r3n To make the fixes to the DAOs in https://github.com/Netflix/conductor-community/tree/main/persistence, won't I need this PR to go through to implement the interface for this? Or is there some process to use a snapshot of the conductor repo for development to implement the MetadataDAO interface for the conductor-community repo? It seems like there is a circular dependency that doesn't seem great for development. Let me know if my question isn't clear. Thanks.
> 
> You can use your branch/fork with the changes, publish them to local maven repository `gradlew publishToMavenLocal` and use that version (you can run `gradlew properties` and check for `Inferred project: conductor, version: ` to find the version.
> 
> With that you will be able to make the changes.

Thanks for the help, @v1r3n. Here are the changes to the conductor-community repo: https://github.com/Netflix/conductor-community/pull/240. Let me know if I'm not doing the changes right for the PR for the community repo.  Thanks.

**Pull request merged**
