### PR TITLE
Adds ES5 REST index DAO for conductor 2.0

### PR DESCRIPTION
**Pull request by bitbier**
With ES5 and later, there is a big push to use the REST client rather than the TCP transport client.
Not only that, but some services such as AWS ElasticSearch only support the HTTP REST client. This
is an attempt to add the ES 5 REST client for conductor.

This is me attempting to add this to Conductor 2.0. There is [another PR](https://github.com/Netflix/conductor/pull/803) to add this to Conductor 1.12.

### CODE REVIEW

**Comment by bitbier** [comment]
Oy vey. Will probably work on improving the coverage later. But if anyone wants to take this and run with it. Please feel free. I'm no longer really working on conductor integration anymore.

**Comment by davidwadden** [comment]
@bitbier There's something in this change that's causing `conductor-server` to be built as version `1.12.4-SNAPSHOT` instead of `2.1.0-SNAPSHOT` .. It's not apparent to me why though.  I'll take a closer look at that and help out with getting some test coverage to get this merged.  

I'll follow up to coordinate updating this PR with that work.

**Comment by davidwadden** [comment]
@bitbier please take a look at [**davidwadden/conductor#es-5-rest-module-2.0-refactor**](https://github.com/davidwadden/conductor/commits/es-5-rest-module-2.0-refactor) for my progress so far.

I started with changing around the integration test setup to DRY the same integration test used for ES Transport Client on Dynomite/Redis backend.  High-confidence integration tests were maybe most important to me.  I did need to add some async polling following indexing new documents in a couple places.

I changed the test setup on [`TestElasticSearchRestDAOV5.java`](https://github.com/davidwadden/conductor/commit/7c390013ebe27ef6c2c1f911d385bd0c0aac7be3#diff-69032ee58472c9e9e97bc4c53e5755c8) to create and destroy the indices for every test method and added some coverage.

Looking for any feedback as I work through getting happy path coverage on the DAO itself.

**Comment by mudit3774** [comment]
@cyzhao Since ES transport client is deprecated in future releases : https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/transport-client.html Is there any plans of merging this / completing this PR ?

**Comment by davidwadden** [comment]
@mudit3774 I've improved test coverage over at https://github.com/davidwadden/conductor/commits/es5-rest-client and was going to open a new PR since the original submitter hasn't gotten back to me.  It's not perfect yet but good enough to get a code review I think.  I didn't change production code too much, mostly backfilling tests;  both end-to-end and unit.

**Comment by apanicker-nflx** [comment]
Merged #887 which extends from this.

**Pull request closed without merging**
