### PR TITLE
Back-porting Dynamic fork bug PR #2433 to 2.31

### PR DESCRIPTION
**Pull request by james-deee**
Pull Request type
----
- [X ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

This backports the fix made in this PR that is merged into V3: https://github.com/Netflix/conductor/pull/2443

It fixes a bug with Dynamic workflows possibly not getting a task back due to a task reference name collision somewhere else in the workflow.

### CODE REVIEW

**Comment by james-deee** [comment]
@aravindanr any advice here? Not sure how to kick off the above build issue?

**Comment by james-deee** [comment]
@apanicker-nflx or @aravindanr ? Any help here?

**Comment by aravindanr** [comment]
@james-deee Sorry about the delay. This slipped through the cracks. The Github workflow is not working correctly. Could you rebase from Netflix:2.31 into your fork and run the checks again?

**Comment by james-deee** [comment]
@aravindanr this build failed. Is it a change to using Java 11 over here in 2.31 land? I bet it used to compile with Java 8? There's now a failure it looks like: 

```
> Task :conductor-contribs:javadoc
                       ^
  symbol:   class PreDestroy
  location: package javax.annotation
/home/runner/work/conductor/conductor/contribs/src/main/java/com/netflix/conductor/contribs/listener/ArchivingWithTTLWorkflowStatusListener.java:53: error: cannot find symbol
2 errors
    @PreDestroy
```

**Comment by aravindanr** [comment]
Looks like it. I switched the ci build to use Java 8. Can you rebase and try again?

**Comment by james-deee** [comment]
@aravindanr that did it. Can you merge this when you get a chance? Thanks.

**Review by apanicker-nflx — APPROVED** [review]

**Pull request merged**
