### PR TITLE
Add support for publishing and subscribing to NATS

### PR DESCRIPTION
**Pull request by heajuenhwang**
Issue was created. 
https://github.com/Netflix/conductor/issues/310

@v1r3n
As @toddschilling mentioned we built the the Nats/Nats streaming integration on conductor.
Just raise the pull request. Can you please review?

1.To publish the message to Nats ( Event Task).
**"sink": "nats:{Nats Subject name}"**
Example:
{
"name": "workflowcompletepublish",
"taskReferenceName": "event_publish",
"inputParameters": {
"Subject": "workflowupdate",
"Name": "workflowupdate",
"Version": "0.0.1",
"Status": {
"Name": "Completed",
"Reason": ""
}
},
"type": "EVENT",
"startDelay": 0,
"sink": "nats:workflowupdate"
}

2. Subscribe the Nats Event (Event Handler).
**"event": "nats:{Nat Subject name}:{QueueName}",**

Example:
{
"name": "status",
"event": "nats:currentstatus:queue1",
"actions": [
{
"action": "start_workflow",
"start_workflow": {
"name": "updatestatus",
"input": {
"payload": "${$}"
}
},
"expandInlineJSON": false
}
],
"active": true
}

### CODE REVIEW

**Comment by v1r3n** [comment]
@heajuenhwang can you send this PR against the `dev` branch?

**Comment by heajuenhwang** [comment]
@v1r3n  Ok I will PR to dev. There is couple of patch we added in the Nats integration. 
We can update those and PR to dev branch.Thanks.

**Comment by v1r3n** [comment]
@heajuenhwang please update the PR against dev so we can merge.

**Comment by v1r3n** [comment]
@heajuenhwang can you open this PR against the dev branch?

**Pull request merged**
