### PR TITLE
Upgrade/preparing for react 16

### PR DESCRIPTION
**Pull request by lordbender**
As part of the modernization of the Express Proxy and React UI, we need to remove the createClass, as this is not supported in React 16+. 

 - Remove React.createClass({}), replacing with class ComponentName extends React.Component {}

### CODE REVIEW

**Comment by cyzhao** [comment]
@mstier-nflx @hunterford please review when you get a chance, thanks

**Comment by lordbender** [comment]
@hunterford I resolved the conflicts. Can you please re-approve and merge these changes when you get a chance?

Thanks.

**Comment by lordbender** [comment]
@mstier-nflx can you please merge this so I can avoid further conflicts?

**Comment by lordbender** [comment]
@hunterford  @cyzhao @mstier-nflx  any feedbak, thoughts, etc? I have the redux upgrade behind this one done, and I am working on the React 16.4 and Router upgrade along with some elastic dash-boarding behind this and my other pull request.

**Pull request merged**
