### PR TITLE
Conductor Server Authentication & Authorization

### PR DESCRIPTION
**Pull request by maheshyaddanapudi**
Pull Request type
----

- [x] Feature
- [x] Bug
- [x] Build related changes

Changes in this PR
----

Addition of feature to secure the APIs exposed by conductor server, based on a role based access, utilizing Spring Security and OAuth2.0. Adds feature https://github.com/Netflix/conductor/discussions/2189
Added Healtcheck to Dockerfile and docker-compose for conductor-server.
Updated Docker Image for Elasticsearch to 6.X in docker-compose as Conductor 3.X defaults to ES6.
Updated Conductor Server Docker file to be jdk 11 based as 3.X is Spring Boot and jdk 11 compatible. Fixes https://github.com/Netflix/conductor/discussions/2191 possibly.
Added new docker-compose-secure.yaml with default OAuth2.0 provider keycloak and conductor container in secure mode i.e. with Spring Security

The confg file being passed as a parameter was not being picked up by the JAR and hence added new method for handling the same.

Enabled indexing on docker-compose properties by default, as the elasticsearch container is both configured and pointed to, in docker-compose set-up. Fixes https://github.com/Netflix/conductor/issues/2175 possibly

Removed unnecessary imports from few java files.

Alternatives considered
----

No alternatives available other than securing the Jar hosting container (Docker) or host.

### CODE REVIEW

**Comment by apanicker-nflx** [comment]
@maheshyaddanapudi Could you please break this PR into two parts - one which adds Spring Security and another for docker file changes? This would make it easier to review and also also cleanly separate out the changes. Thanks

**Comment by maheshyaddanapudi** [comment]
> @maheshyaddanapudi Could you please break this PR into two parts - one which adds Spring Security and another for docker file changes? This would make it easier to review and also also cleanly separate out the changes. Thanks

@aravindanr I understand. There are a few commits which have both the changes. Hence the easiest or fast way to segregate them for me, would be to delete the forked repo, first checkin the security changes and submit a PR. Once that is done, I can add Docker changes and create another. Does that sound ok ?

**Comment by maheshyaddanapudi** [comment]
Wil create seperate pull requests for securit & docker changes

**Comment by maheshyaddanapudi** [comment]
https://github.com/Netflix/conductor/pull/2200

Created a seperate PR for Security Feature

**Comment by maheshyaddanapudi** [comment]
https://github.com/Netflix/conductor/pull/2206

Created a seperate PR for Docker & Docker Compose Bugs & Features

**Pull request closed without merging**
